name: test-clang-format

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Dependencies
        run: |
          sudo apt-get install clang-format
          find -name '*.cpp' '*.hpp' |xargs clang-format -style=Goolge -i
    
    
